### ISSUE TITLE
Example code from V-EZ docs

### ISSUE THREAD

**Issue by codecnotsupported** [GPUOpen-LibrariesAndSDKs/V-EZ#11]
From the "Putting It All Together" section.
It wasn't meant to be compilable was it?

**Comment by soconne** [comment]
Thanks for pointing this out, yes it should have been compilable but the old API prefix "vk" was missed in a few places in the docs.  The new prefix is "vez".  I'll correct it.

**Comment by codecnotsupported** [comment]
![Month Actually](https://i.ytimg.com/vi/vwW-amtGOWI/hqdefault.jpg)

**Comment by soconne** [comment]
Fixed in e982a3f72bd18dcd5c2374de12d0a832621d2d74

**Comment by codecnotsupported** [comment]
Still failed to compile.
I think it might be more useful if I posted the output of g++.

```
00:24:38 **** Incremental Build of configuration Debug for project V-EZ ****
make all 
Building file: ../src/V-EZ.cpp
Invoking: GCC C++ Compiler
g++ -I/home/User/Documents/Programming/Libaries/V-EZ/Source -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/V-EZ.d" -MT"src/V-EZ.o" -o "src/V-EZ.o" "../src/V-EZ.cpp"
../src/V-EZ.cpp: In function ‘bool InitVulkanEZ()’:
../src/V-EZ.cpp:44:5: error: ‘VezSurfaceCreateInfo’ was not declared in this scope
     VezSurfaceCreateInfo surfaceCreateInfo = {};
     ^~~~~~~~~~~~~~~~~~~~
../src/V-EZ.cpp:44:5: note: suggested alternative: ‘VezImageCreateInfo’
     VezSurfaceCreateInfo surfaceCreateInfo = {};
     ^~~~~~~~~~~~~~~~~~~~
     VezImageCreateInfo
../src/V-EZ.cpp:45:5: error: ‘surfaceCreateInfo’ was not declared in this scope
     surfaceCreateInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~~~~~~~~
../src/V-EZ.cpp:45:5: note: suggested alternative: ‘instanceCreateInfo’
     surfaceCreateInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~~~~~~~~
     instanceCreateInfo
../src/V-EZ.cpp:45:35: error: ‘GetModuleHandle’ was not declared in this scope
     surfaceCreateInfo.hinstance = GetModuleHandle(nullptr);
                                   ^~~~~~~~~~~~~~~
../src/V-EZ.cpp:46:30: error: ‘glfwGetWin32Window’ was not declared in this scope
     surfaceCreateInfo.hwnd = glfwGetWin32Window(window);
                              ^~~~~~~~~~~~~~~~~~
../src/V-EZ.cpp:46:30: note: suggested alternative: ‘glfwGetX11Window’
     surfaceCreateInfo.hwnd = glfwGetWin32Window(window);
                              ^~~~~~~~~~~~~~~~~~
                              glfwGetX11Window
../src/V-EZ.cpp:47:14: error: ‘vezCreateSurface’ was not declared in this scope
     result = vezCreateSurface(instance, &surfaceCreateInfo, &surface);
              ^~~~~~~~~~~~~~~~
../src/V-EZ.cpp:47:14: note: suggested alternative: ‘vezCreateImage’
     result = vezCreateSurface(instance, &surfaceCreateInfo, &surface);
              ^~~~~~~~~~~~~~~~
              vezCreateImage
../src/V-EZ.cpp:55:10: error: ‘vector’ is not a member of ‘std’
     std::vector<VkPhysicalDevice> physicalDevices(physicalDeviceCount);
          ^~~~~~
../src/V-EZ.cpp:55:33: error: expected primary-expression before ‘>’ token
     std::vector<VkPhysicalDevice> physicalDevices(physicalDeviceCount);
                                 ^
../src/V-EZ.cpp:55:35: error: ‘physicalDevices’ was not declared in this scope
     std::vector<VkPhysicalDevice> physicalDevices(physicalDeviceCount);
                                   ^~~~~~~~~~~~~~~
../src/V-EZ.cpp:55:35: note: suggested alternative: ‘physicalDevice’
     std::vector<VkPhysicalDevice> physicalDevices(physicalDeviceCount);
                                   ^~~~~~~~~~~~~~~
                                   physicalDevice
../src/V-EZ.cpp:58:20: error: unable to deduce ‘auto&&’ from ‘physicalDevices’
     for (auto pd : physicalDevices)
                    ^~~~~~~~~~~~~~~
../src/V-EZ.cpp:73:26: error: expected ‘;’ before ‘createInfo’
     VezSurfaceCreateInfo createInfo = {};
                          ^~~~~~~~~~
../src/V-EZ.cpp:74:5: error: ‘createInfo’ was not declared in this scope
     createInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~
../src/V-EZ.cpp:74:5: note: suggested alternative: ‘appInfo’
     createInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~
     appInfo
../src/V-EZ.cpp: In function ‘int main(int, char**)’:
../src/V-EZ.cpp:101:10: error: ‘InitGLFW’ was not declared in this scope
     if (!InitGLFW())
          ^~~~~~~~
make: *** [src/V-EZ.o] Error 1
src/subdir.mk:18: recipe for target 'src/V-EZ.o' failed


```

**Comment by codecnotsupported** [comment]
I made some adjustments...
#include <V-EZ.h> should be "#include <VEZ.h>"
"appinfo.engineVersion"  should be "appInfo.engineVersion"  (capital "I")
I included vector cause it was used.

But it still fails to compile.
Because "VezSurfaceCreateInfo" is undefined in VEZ.h

I think it might be more useful if I posted the output of g++ with those changes.

```
**** Incremental Build of configuration Debug for project V-EZ ****
make all 
Building file: ../src/V-EZ.cpp
Invoking: GCC C++ Compiler
g++ -I/home/User/Documents/Programming/Libaries/V-EZ/Source -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/V-EZ.d" -MT"src/V-EZ.o" -o "src/V-EZ.o" "../src/V-EZ.cpp"
../src/V-EZ.cpp: In function ‘bool InitVulkanEZ()’:
../src/V-EZ.cpp:45:5: error: ‘VezSurfaceCreateInfo’ was not declared in this scope
     VezSurfaceCreateInfo surfaceCreateInfo = {};
     ^~~~~~~~~~~~~~~~~~~~
../src/V-EZ.cpp:45:5: note: suggested alternative: ‘VezImageCreateInfo’
     VezSurfaceCreateInfo surfaceCreateInfo = {};
     ^~~~~~~~~~~~~~~~~~~~
     VezImageCreateInfo
../src/V-EZ.cpp:46:5: error: ‘surfaceCreateInfo’ was not declared in this scope
     surfaceCreateInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~~~~~~~~
../src/V-EZ.cpp:46:5: note: suggested alternative: ‘instanceCreateInfo’
     surfaceCreateInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~~~~~~~~
     instanceCreateInfo
../src/V-EZ.cpp:46:35: error: ‘GetModuleHandle’ was not declared in this scope
     surfaceCreateInfo.hinstance = GetModuleHandle(nullptr);
                                   ^~~~~~~~~~~~~~~
../src/V-EZ.cpp:47:30: error: ‘glfwGetWin32Window’ was not declared in this scope
     surfaceCreateInfo.hwnd = glfwGetWin32Window(window);
                              ^~~~~~~~~~~~~~~~~~
../src/V-EZ.cpp:47:30: note: suggested alternative: ‘glfwGetX11Window’
     surfaceCreateInfo.hwnd = glfwGetWin32Window(window);
                              ^~~~~~~~~~~~~~~~~~
                              glfwGetX11Window
../src/V-EZ.cpp:48:14: error: ‘vezCreateSurface’ was not declared in this scope
     result = vezCreateSurface(instance, &surfaceCreateInfo, &surface);
              ^~~~~~~~~~~~~~~~
../src/V-EZ.cpp:48:14: note: suggested alternative: ‘vezCreateImage’
     result = vezCreateSurface(instance, &surfaceCreateInfo, &surface);
              ^~~~~~~~~~~~~~~~
              vezCreateImage
../src/V-EZ.cpp:74:26: error: expected ‘;’ before ‘createInfo’
     VezSurfaceCreateInfo createInfo = {};
                          ^~~~~~~~~~
../src/V-EZ.cpp:75:5: error: ‘createInfo’ was not declared in this scope
     createInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~
../src/V-EZ.cpp:75:5: note: suggested alternative: ‘appInfo’
     createInfo.hinstance = GetModuleHandle(nullptr);
     ^~~~~~~~~~
     appInfo
../src/V-EZ.cpp: In function ‘int main(int, char**)’:
../src/V-EZ.cpp:102:10: error: ‘InitGLFW’ was not declared in this scope
     if (!InitGLFW())
          ^~~~~~~~
src/subdir.mk:18: recipe for target 'src/V-EZ.o' failed
make: *** [src/V-EZ.o] Error 1

```
